---
kind: pipeline
name: windows-amd64

platform:
  os: windows
  arch: amd64

steps:
- name: dryrun
  pull: always
  image: plugins/docker:windows-amd64
  settings:
    dockerfile: docker/Dockerfile.windows.amd64
    dry_run: true
    password:
      from_secret: docker_password
    repo: plugins/base
    tags: windows-amd64
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:windows-amd64
  settings:
    auto_tag: true
    auto_tag_suffix: windows-amd64
    dockerfile: docker/Dockerfile.windows.amd64
    password:
      from_secret: docker_password
    repo: plugins/base
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  branch:
  - master
