---
kind: pipeline
name: windows-1809

platform:
  os: windows
  arch: amd64
  version: 1809

steps:
- name: dryrun
  pull: always
  image: plugins/docker:windows-1809
  settings:
    dockerfile: docker/Dockerfile.windows.1809
    dry_run: true
    password:
      from_secret: docker_password
    repo: plugins/base
    tags: windows-1809
    username:
      from_secret: docker_username
  when:
    event:
    - pull_request

- name: publish
  pull: always
  image: plugins/docker:windows-1809
  settings:
    auto_tag: true
    auto_tag_suffix: windows-1809
    dockerfile: docker/Dockerfile.windows.1809
    password:
      from_secret: docker_password
    repo: plugins/base
    username:
      from_secret: docker_username
  when:
    event:
    - push

trigger:
  branch:
  - master
